//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_CursoBasico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int AlunoID { get; set; }
        public string AlunoNome { get; set; }
        public Nullable<int> PadraoID { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Padrao Padrao { get; set; }
    }
}
