//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_CursoBasico
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_AlunoCurso
    {
        public int AlunoID { get; set; }
        public string AlunoNome { get; set; }
        public int CursoID { get; set; }
        public string CursoNome { get; set; }
    }
}
